name: examples
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/ccache
          key: ${{ runner.os }}-ccache
          restore-keys: ${{ runner.os }}-ccache
      - name: Build examples
        run: |
          echo "Processing linux-based builds..."
          for dir in examples/*/; do
              if [[ ${dir} == *"raspberry"* ]]; then
                  echo "Entering directory: $dir"
                  cd "$dir"
                  if [ -f "CMakeLists.txt" ]; then
                      echo "Running cmake build in $dir"
                      mkdir -p build
                      cd build
                      cmake ..
                      make
                      cd ../../..
                  else
                      echo "No CMakeLists.txt found in $dir, skipping..."
                      cd ../..
                  fi
              fi
          done

          export IDF_TARGET=$(echo "esp32" | tr '[:upper:]' '[:lower:]' | tr -d '_-')
          export CCACHE_DIR="${HOME}/ccache"
          mkdir -p ${CCACHE_DIR}
          echo -e "\nProcessing esp builds..."
          for dir in examples/*/; do
              if [[ ${dir} != *"raspberry"* && ${dir} != *"common"* && ${dir} != *"cubeide"* ]]; then
                  echo "Building: $dir"
                  cd "$dir"
                  docker run -t -e IDF_TARGET="${IDF_TARGET}" -e CCACHE_DIR=/ccache -v ${CCACHE_DIR}:/ccache -v "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" \
                  -w "/app/${{ github.repository }}" espressif/idf:v5.1.2 \
                  /bin/bash -c 'git config --global --add safe.directory "*" && cd ${dir} && idf.py build'
                  cd ../..
              fi
          done
          
        shell: bash